version: '3.6'

services:
  mongo:
    image: mongo    
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
    env_file: .env
    volumes:
      - /data/experiments/db:/data/db

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["--mu", "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo:27017/$MONGO_DATABASE?authSource=admin"]
    ports:
      - 127.0.0.1:9000:9000
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo