version: '3.6'

services:
  mongo:
    image: mongo    
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
    env_file: .env

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["--mu", "mongodb://mongo_user:mongo_password@mongo:27017/$MONGO_DATABASE?authSource=admin"]
    ports:
      - 127.0.0.1:9000:9000
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo